scikit-learn knn

In [0]:
# -*- coding: utf-8 -*-
# usage: scikit-learn_nv.py
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import neighbors

print("news words")
label=(["政治", "経済", "スポーツ"])
word = np.array([[0,1,0,0,1,1,1,0,0], # 政治　politics
                 [0,2,0,0,1,1,1,0,0], 
                 [0,1,0,0,2,1,1,0,0], 
                 [0,1,0,0,1,2,1,0,0], 
                 [0,1,0,0,1,1,2,0,0], 
                 [0,3,0,0,1,1,1,0,0], 
                 [0,1,0,0,3,3,3,0,0], 
                 [0,2,0,0,2,1,1,0,0], 
                 [0,1,0,0,1,2,2,0,0], 
                 [0,2,0,0,2,2,2,0,0], 
                 [0,0,1,0,0,0,2,1,0], # 経済 economy
                 [0,0,1,0,0,0,1,1,0], 
                 [0,0,2,0,0,0,2,1,0], 
                 [0,0,1,0,0,0,2,2,0], 
                 [0,0,2,0,0,0,2,2,0], 
                 [0,0,3,0,0,0,2,1,0], 
                 [0,0,1,0,0,0,3,1,0], 
                 [0,0,1,0,0,0,2,3,0], 
                 [0,0,3,0,0,0,2,3,0], 
                 [0,0,3,0,0,0,1,3,0], 
                 [1,0,0,1,0,0,1,0,0], # スポーツ sports
                 [2,0,0,1,0,0,1,0,0],
                 [1,0,0,2,0,0,1,0,0],
                 [1,0,0,1,0,0,2,0,0],
                 [2,0,0,2,0,0,1,0,0],
                 [2,0,0,2,0,0,2,0,0],
                 [3,0,0,1,0,0,1,0,0],
                 [1,0,0,3,0,0,1,0,0],
                 [1,0,0,1,0,0,3,0,0],
                 [3,0,0,3,0,0,3,0,0]]) 

ctg = np.array([0,0,0,0,0,0,0,0,0,0,
                1,1,1,1,1,1,1,1,1,1,
                2,2,2,2,2,2,2,2,2,2]) # 分野のラベル category label

x = np.array([[0,0,1,0,1,0,0,1,0],  # x1
              [0,0,0,1,0,1,1,0,1]]) # x2

num=int(input('k of kNN= '))
knn=neighbors.KNeighborsClassifier(n_neighbors=num)
knn.fit(word, ctg)
results=knn.predict(x)
print(results, end="")
print(label[results[0]], end="")
print(label[results[1]])
print()

###
print("digits")
# load digits
from sklearn.datasets import load_digits
digits=load_digits()
#トレーニングデータとテストデータに分割
data_train, data_test, label_train, label_test = train_test_split(digits.data, digits.target, test_size=0.10)

from sklearn.metrics import f1_score

dnum=int(input('k of kNN= '))
dknn=neighbors.KNeighborsClassifier(n_neighbors=dnum)
dknn.fit(data_train, label_train)
label_predict=dknn.predict(data_test)
print("test")
print(label_test)
print("predict")
print(label_predict)

print("\nF-measure (micro average)=", end="")
print(f1_score(label_test, label_predict, average='micro'))
print("\nconfusion matrix")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(label_test, label_predict))


news words
k of kNN= 5
[1 2]経済スポーツ

digits
k of kNN= 5
test
[2 9 8 5 4 4 6 4 4 9 1 2 6 2 9 1 5 4 7 6 0 8 4 3 4 9 7 6 1 5 7 5 4 4 2 3 2
 5 9 5 5 3 4 9 9 4 6 9 8 8 4 2 5 5 3 0 7 1 1 5 3 9 2 0 9 4 4 1 4 2 9 7 9 9
 8 4 7 6 6 7 4 3 8 4 7 6 6 7 4 2 6 8 1 5 6 5 8 7 1 0 0 5 0 9 9 5 8 1 0 9 6
 3 0 3 3 6 4 9 3 9 9 9 9 6 0 5 5 4 7 4 6 2 9 5 2 3 1 7 3 3 0 2 1 5 1 9 4 4
 8 1 7 1 9 2 9 1 0 9 8 6 2 1 5 0 3 0 8 8 0 0 8 9 6 3 3 3 1 2 3 7]
predict
[2 9 8 5 4 4 6 4 4 9 1 2 6 2 9 1 5 4 7 6 0 8 4 3 4 9 7 6 1 6 7 5 4 4 2 3 2
 5 9 5 5 3 4 9 9 4 6 3 8 8 4 2 5 5 3 0 7 1 1 5 3 9 2 0 9 4 4 1 4 2 9 7 9 9
 8 4 7 6 6 9 4 3 8 4 7 6 6 7 4 2 6 8 1 5 6 5 8 7 1 0 0 5 0 9 9 5 1 1 0 9 6
 3 0 3 3 6 4 9 3 9 9 9 9 6 0 5 5 4 7 4 6 2 9 5 2 3 1 7 3 3 0 2 1 5 1 9 4 4
 8 1 7 1 9 2 9 1 0 9 8 6 2 1 5 0 3 0 8 8 0 0 8 9 6 3 3 3 1 2 3 7]

F-measure (micro average)=0.9777777777777777

confusion matrix
[[15  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0]
 [ 0